config/routes.rb
Rails.application.routes.draw do
  get 'menu/index'
  devise_for :users
  resources :products

  root 'pages#home'

  get 'menu', to: "menu#index"  
  get 'catering', to: "pages#catering"
  get 'info', to: "pages#info"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @page = 'menu'
    @products = Product.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @page = 'home'
  end
  

  def catering
    @page = 'catering'
  end
  
  def info
    @page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :dairy_free, :gluten_free, :kosher, :peanut_free, :vegan, :vegetarian, :available, :catering, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_links.html.erb
<div class="col-2">

  <h5 class="link-container">
    <%= link_to "Home", root_path, class: "link #{@page == 'home' ? 'active': '' }"%>
  </h5>
  <h5 class="link-container">
    <%= link_to "Menu", menu_path, class: "link #{@page == 'menu' ? 'active': '' }"%>
  </h5>
  <h5 class="link-container">
    <%= link_to "Catering", catering_path, class: "link #{@page == 'catering' ? 'active': '' }"%>
  </h5>
  <h5 class="link-container">
    <%= link_to "More info", info_path, class: "link #{@page == 'info' ? 'active': '' }"%>
  </h5>
  <h5 class="link-container">
    <%= link_to "Customer Reviews", "", class: "link #{@page == 'reviews' ? 'active': '' }"%>
  </h5>

</div>

app/views/layouts/_navbar.html.erb
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

app/views/layouts/_title.html.erb
<div class="title-card">
    <h1 class="title-text">
        Frank's Foods
    </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">  
  </head>

  <body>
  <% cache do %>
    <div class="<%= @page %>-page">
        <div class="row page-container">
            <%= render 'layouts/links'%>
            <div class="col-8">
                <% unless @page == "home"%>
                <%= render 'layouts/title'%>
                <% end %>
                <%= yield %>
            </div>
            <div class="col-2"></div>
        </div>
    </div
    <%end%>
  </body>
</html>

app/views/menu/index.html.erb
<div class="menu-container">
    <div class="row">
        <% 3.times do %>
        <% @products.each do |product| %>
        <div class="col-4">
          <div class="card mb-2">
          
            <h5 class = 'text-center'><%=product.name%></h5>
            <p><%= product.description %></p>
            <span><%= product.price %> | <%= product.catering ? "Available for catering" : "" %>
        
          </div>
        </div>
        <% end %>
        <% end %>
    </div>
</div>

app/views/pages/catering.html.erb
<h1>Pages#catering</h1>
<p>Find me in app/views/pages/catering.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/catering.html.erb</p>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :dairy_free %>
    <%= form.check_box :dairy_free %>
  </div>

  <div class="field">
    <%= form.label :gluten_free %>
    <%= form.check_box :gluten_free %>
  </div>

  <div class="field">
    <%= form.label :kosher %>
    <%= form.check_box :kosher %>
  </div>

  <div class="field">
    <%= form.label :peanut_free %>
    <%= form.check_box :peanut_free %>
  </div>

  <div class="field">
    <%= form.label :vegan %>
    <%= form.check_box :vegan %>
  </div>

  <div class="field">
    <%= form.label :vegetarian %>
    <%= form.check_box :vegetarian %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="field">
    <%= form.label :catering %>
    <%= form.check_box :catering %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Dairy free</th>
      <th>Gluten free</th>
      <th>Kosher</th>
      <th>Peanut free</th>
      <th>Vegan</th>
      <th>Vegetarian</th>
      <th>Available</th>
      <th>Catering</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.dairy_free %></td>
        <td><%= product.gluten_free %></td>
        <td><%= product.kosher %></td>
        <td><%= product.peanut_free %></td>
        <td><%= product.vegan %></td>
        <td><%= product.vegetarian %></td>
        <td><%= product.available %></td>
        <td><%= product.catering %></td>
        <td><%= product.featured %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Dairy free:</strong>
  <%= @product.dairy_free %>
</p>

<p>
  <strong>Gluten free:</strong>
  <%= @product.gluten_free %>
</p>

<p>
  <strong>Kosher:</strong>
  <%= @product.kosher %>
</p>

<p>
  <strong>Peanut free:</strong>
  <%= @product.peanut_free %>
</p>

<p>
  <strong>Vegan:</strong>
  <%= @product.vegan %>
</p>

<p>
  <strong>Vegetarian:</strong>
  <%= @product.vegetarian %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<p>
  <strong>Catering:</strong>
  <%= @product.catering %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @product.featured %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>